default_model: qwen_7b

models:

  qwen_1_5b:
    model_id: Qwen/Qwen2.5-1.5B-Instruct

    generation:
      do_sample: false
      repetition_penalty: 1.05
      max_new_tokens: 512

    tokenizer:
      truncation: true
      max_input_tokens: 4096
      use_chat_template: true
      skip_special_tokens: true

    runtime:
      device: auto
      dtype: auto

  qwen_7b:
    model_id: Qwen/Qwen2.5-7B-Instruct

    generation:
      do_sample: false
      repetition_penalty: 1.05
      max_new_tokens: 768

    tokenizer:
      truncation: true
      max_input_tokens: 8192
      use_chat_template: true
      skip_special_tokens: true

    runtime:
      device: auto
      dtype: auto

  medgemma_1_5_4b:
    model_id: google/medgemma-1.5-4b-it

    generation:
      do_sample: false
      repetition_penalty: 1.05
      max_new_tokens: 1200

    tokenizer:
      truncation: true
      max_input_tokens: 3500
      use_chat_template: false
      skip_special_tokens: false

    runtime:
      device: auto
      dtype: auto
      device_map: auto

    quantization:
      load_in_4bit: true
      bnb_4bit_compute_dtype: float16
      bnb_4bit_use_double_quant: true
      bnb_4bit_quant_type: nf4